# Generated by Django 4.0 on 2022-09-07 05:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipe_identification', models.CharField(choices=[('cédula', 'cédula'), ('cédula de extrangería', 'cédula de extrangería'), ('pasaporte', 'pasaporte'), ('targeta de identidad', 'targeta de identidad')], max_length=42)),
                ('identification_number', models.CharField(max_length=10, unique=True)),
                ('names', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=300, unique=True)),
                ('hobbie', models.CharField(max_length=200)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
    ]
